overrides:
  'vue': 'rc'
  '@vue/compiler-core': 'rc'
  '@vue/compiler-dom': 'rc'
  '@vue/compiler-sfc': 'rc'
  '@vue/compiler-ssr': 'rc'
  '@vue/compiler-vapor': 'rc'
  '@vue/reactivity': 'rc'
  '@vue/runtime-core': 'rc'
  '@vue/runtime-dom': 'rc'
  '@vue/runtime-vapor': 'rc'
  '@vue/server-renderer': 'rc'
  '@vue/shared': 'rc'
  '@vue/compat': 'rc'

peerDependencyRules:
  allowAny:
    - 'vue'
